# Generated by Django 5.2.8 on 2025-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pogoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50, unique=True)),
                ('szerokosc_geo', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dlugosc_geo', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('czas', models.DateTimeField()),
            ],
            options={
                'db_table': 'pogoda',
            },
        ),
    ]
