# Generated by Django 5.2.8 on 2025-11-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda_app', '0002_city_weatherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pogoda',
        ),
    ]
