# Generated by Django 5.2.8 on 2025-11-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda_app', '0003_delete_pogoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('date', models.DateField()),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_readings', to='pogoda_app.city')),
            ],
            options={
                'db_table': 'pogoda_historical',
                'ordering': ['-date'],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
