# Generated by Django 5.2.8 on 2025-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda_app', '0004_historicalweatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
