# Generated by Django 5.2.8 on 2025-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda_app', '0005_weatherdata_precipitation_weatherdata_wind_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweatherdata',
            name='relative_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='relative_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
