# Generated by Django 5.2.8 on 2025-11-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda_app', '0006_historicalweatherdata_relative_humidity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalWeatherData',
        ),
    ]
